### ISSUE TITLE
CSS not found

### ISSUE THREAD

**Issue by babichss** [resir014/Clear-Sans-Webfont#2]
https://cdn.rawgit.com/resir014/Clear-Sans-Webfont/v0.1.0/css/clear-sans.css : 404

**Comment by resir014** [comment]
Hey @babichss!

The CDN URL was intended for when we reach v1.0.0 but I forgot to work on this. Will publish tonight.

**Comment by resir014** [comment]
Fixed. You can use the following CDN URL now:
https://cdn.rawgit.com/resir014/Clear-Sans-Webfont/v1.0.0/css/clear-sans.css
