### ISSUE TITLE
Add WOFF2

### ISSUE THREAD

**Issue by ghost** [resir014/Clear-Sans-Webfont#3]
Because it's 2016 and it's hip to compress stuff further.

Side note: I would do this myself but I just happen to be hours away from going to bed.

**Comment by domschmidt** [comment]
Yeah it would be very nice if you could add the woff2 format.

Thank you

**Comment by ghost** [comment]
Here is a conversion from WOFF to WOFF2: [woff2-convert.zip](https://github.com/resir014/Clear-Sans-Webfont/files/783285/woff2-convert.zip)

**Comment by resir014** [comment]
@citrusui Thanks, I'll add these shortly!
