### ISSUE TITLE
Troubles with Cyrillic in Windows

### ISSUE THREAD

**Issue by Daniil-Pabolkov** [resir014/Clear-Sans-Webfont#6]
Hi, I have some troubles with display this font on Windows in Google Chrome and MS Edge (wasn't check in other browsers).

How it looks on Windows:
 _(Google Chrome; font-size: 16px; font-weight: 700)_
![clearsans-16px-windows](https://user-images.githubusercontent.com/15813062/39221591-46769d3e-487b-11e8-8918-c5e86cf424d1.png)

----

How it look on Ubuntu:
_(Google Chrome; font-size: 16px; font-weight: 700)_
![clearsans-16px-ubuntu](https://user-images.githubusercontent.com/15813062/39221664-a629195a-487b-11e8-9db8-68f26f8663ba.png)

Font size of 16px on Ubuntu  seems bigger than on Windows, thus I add screenshot with 15px font size (for comparison)
_(Google Chrome; font-size: 15px; font-weight: 700)_
![clearsans-15px-ubuntu](https://user-images.githubusercontent.com/15813062/39221730-19fce4c4-487c-11e8-8787-ba8ed9eb1f7b.png)

----

As you can see, on Ubuntu fonts with Cyrillic looks good, but on Windows its has artifacts.

**Comment by resir014** [comment]
Hi @Daniil-Pabolkov,

I no longer have the time to maintain this package but I never found the time to properly deprecate it, sorry!

In the meantime, you might want to look at: https://github.com/KyleAMathews/typefaces/tree/master/packages/clear-sans
